# Generated by Django 4.2.7 on 2025-10-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audiotranscript_clinicaldata_clinicalreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicaldata',
            options={'ordering': ['-extracted_at'], 'verbose_name': 'Dati Clinici', 'verbose_name_plural': 'Dati Clinici'},
        ),
    ]
