name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
          pip install django djangorestframework mongoengine django-environ django-cors-headers
          # Mock dependencies to avoid import errors
          pip install --no-deps reportlab Pillow

      - name: Configure Django settings
        run: |
          cd backend
          export DJANGO_SETTINGS_MODULE=medical_system.settings
          export SECRET_KEY="dummy-secret-key-for-docs"
          export DEBUG=False
          export ALLOWED_HOSTS="localhost"
          
      - name: Generate API documentation
        run: |
          cd docs
          sphinx-apidoc -o ./source ../backend -f --module-first
          # Remove the modules.rst file to avoid warnings (consistent with local setup)
          rm -f source/modules.rst
          # Apply medical_workflow_views documentation fix
          if [ -f api_fix.py ]; then
            python api_fix.py
          fi
          
      - name: List generated files
        run: |
          echo "Generated RST files:"
          ls -la docs/source/
          
      - name: Build Sphinx documentation
        run: |
          cd docs
          # Build without treating warnings as errors since we handle them properly
          python -m sphinx -M html source build -E --keep-going
          
      - name: Add .nojekyll file
        run: |
          touch docs/build/html/.nojekyll
          
      - name: Verify documentation language and content
        run: |
          echo "Checking if documentation is in English..."
          if grep -q "ER-Voice2Text Documentation" docs/build/html/index.html; then
            echo "✓ Documentation is in English"
          else
            echo "⚠ Warning: Documentation might not be in English"
          fi
          
          if grep -q "medical_workflow_views" docs/build/html/api.html; then
            echo "✓ Medical workflow views are documented"
          else
            echo "⚠ Warning: Medical workflow views might not be documented"
          fi
          
      - name: List build output
        run: |
          echo "Build output:"
          ls -la docs/build/html/
          
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4